export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"; //FIRING SAGA
export const GET_ORDERS_RECEIVE = "GET_ORDERS_RECEIVE"; // STORE RES
export const SORT_STATUS = "SORT_STATUS";
export const SEARCH_NAME = "SEARCH_NAME";
export const SELECT_TOTAL = "SELECT_TOTAL";
 export const UPDATE_TABLE = "UPDATE_TABLE";
 export const  FIRST_PAGE = "FIRST_PAGE "